// Code generated by protoc-gen-go. DO NOT EDIT.
// source: postexample.proto

/*
Package protoBuff is a generated protocol buffer package.

It is generated from these files:
	postexample.proto

It has these top-level messages:
	Maps
	Marker
*/
package protoBuff

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Maps struct {
	Markers []*Marker `protobuf:"bytes,1,rep,name=markers" json:"markers,omitempty"`
}

func (m *Maps) Reset()                    { *m = Maps{} }
func (m *Maps) String() string            { return proto.CompactTextString(m) }
func (*Maps) ProtoMessage()               {}
func (*Maps) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Maps) GetMarkers() []*Marker {
	if m != nil {
		return m.Markers
	}
	return nil
}

type Marker struct {
	Point         int32  `protobuf:"varint,1,opt,name=point" json:"point,omitempty"`
	HomeTeam      string `protobuf:"bytes,2,opt,name=homeTeam" json:"homeTeam,omitempty"`
	AwayTeam      string `protobuf:"bytes,3,opt,name=awayTeam" json:"awayTeam,omitempty"`
	MarkerImage   string `protobuf:"bytes,4,opt,name=markerImage" json:"markerImage,omitempty"`
	Information   string `protobuf:"bytes,5,opt,name=information" json:"information,omitempty"`
	Fixture       string `protobuf:"bytes,6,opt,name=fixture" json:"fixture,omitempty"`
	Capacity      string `protobuf:"bytes,7,opt,name=capacity" json:"capacity,omitempty"`
	PreviousScore string `protobuf:"bytes,8,opt,name=previousScore" json:"previousScore,omitempty"`
	Tv            string `protobuf:"bytes,9,opt,name=tv" json:"tv,omitempty"`
}

func (m *Marker) Reset()                    { *m = Marker{} }
func (m *Marker) String() string            { return proto.CompactTextString(m) }
func (*Marker) ProtoMessage()               {}
func (*Marker) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Marker) GetPoint() int32 {
	if m != nil {
		return m.Point
	}
	return 0
}

func (m *Marker) GetHomeTeam() string {
	if m != nil {
		return m.HomeTeam
	}
	return ""
}

func (m *Marker) GetAwayTeam() string {
	if m != nil {
		return m.AwayTeam
	}
	return ""
}

func (m *Marker) GetMarkerImage() string {
	if m != nil {
		return m.MarkerImage
	}
	return ""
}

func (m *Marker) GetInformation() string {
	if m != nil {
		return m.Information
	}
	return ""
}

func (m *Marker) GetFixture() string {
	if m != nil {
		return m.Fixture
	}
	return ""
}

func (m *Marker) GetCapacity() string {
	if m != nil {
		return m.Capacity
	}
	return ""
}

func (m *Marker) GetPreviousScore() string {
	if m != nil {
		return m.PreviousScore
	}
	return ""
}

func (m *Marker) GetTv() string {
	if m != nil {
		return m.Tv
	}
	return ""
}

func init() {
	proto.RegisterType((*Maps)(nil), "protoBuff.Maps")
	proto.RegisterType((*Marker)(nil), "protoBuff.Marker")
}

func init() { proto.RegisterFile("postexample.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 242 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x86, 0x49, 0xda, 0x24, 0xcd, 0x14, 0x85, 0x2e, 0x1e, 0x06, 0x4f, 0xa1, 0x78, 0x08, 0x08,
	0x39, 0xd8, 0x37, 0xf0, 0xe6, 0xa1, 0x97, 0xe8, 0x0b, 0x8c, 0x61, 0xa3, 0x8b, 0x6e, 0x66, 0xd9,
	0x6c, 0x62, 0xfb, 0x02, 0x3e, 0xb7, 0x64, 0x97, 0x2d, 0xf5, 0xb4, 0x7c, 0xff, 0xf7, 0xc1, 0xc0,
	0xc2, 0xce, 0xf0, 0xe8, 0xe4, 0x89, 0xb4, 0xf9, 0x96, 0x8d, 0xb1, 0xec, 0x58, 0x94, 0xfe, 0x79,
	0x9e, 0xfa, 0x7e, 0x7f, 0x80, 0xf5, 0x91, 0xcc, 0x28, 0x1e, 0xa1, 0xd0, 0x64, 0xbf, 0xa4, 0x1d,
	0x31, 0xa9, 0x56, 0xf5, 0xf6, 0x69, 0xd7, 0x5c, 0xa2, 0xe6, 0xe8, 0x4d, 0x1b, 0x8b, 0xfd, 0x6f,
	0x0a, 0x79, 0xd8, 0xc4, 0x1d, 0x64, 0x86, 0xd5, 0xe0, 0x30, 0xa9, 0x92, 0x3a, 0x6b, 0x03, 0x88,
	0x7b, 0xd8, 0x7c, 0xb2, 0x96, 0x6f, 0x92, 0x34, 0xa6, 0x55, 0x52, 0x97, 0xed, 0x85, 0x17, 0x47,
	0x3f, 0x74, 0xf6, 0x6e, 0x15, 0x5c, 0x64, 0x51, 0xc1, 0x36, 0xdc, 0x78, 0xd1, 0xf4, 0x21, 0x71,
	0xed, 0xf5, 0xf5, 0xb4, 0x14, 0x6a, 0xe8, 0xd9, 0x6a, 0x72, 0x8a, 0x07, 0xcc, 0x42, 0x71, 0x35,
	0x09, 0x84, 0xa2, 0x57, 0x27, 0x37, 0x59, 0x89, 0xb9, 0xb7, 0x11, 0x97, 0xcb, 0x1d, 0x19, 0xea,
	0x94, 0x3b, 0x63, 0x11, 0x2e, 0x47, 0x16, 0x0f, 0x70, 0x63, 0xac, 0x9c, 0x15, 0x4f, 0xe3, 0x6b,
	0xc7, 0x56, 0xe2, 0xc6, 0x07, 0xff, 0x47, 0x71, 0x0b, 0xa9, 0x9b, 0xb1, 0xf4, 0x2a, 0x75, 0xf3,
	0x7b, 0xee, 0xff, 0xe8, 0xf0, 0x17, 0x00, 0x00, 0xff, 0xff, 0x62, 0x72, 0xfa, 0x38, 0x64, 0x01,
	0x00, 0x00,
}
